version: "3.9"

services:
  twitter-uala:
    build:
      context: ./
      dockerfile: Dockerfile
    image: twitter-uala
    container_name: twitter-uala
    restart: on-failure
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/
      - MONGO_DATABASE=twitter-uala

  mongo:
    image: mongo:4.0
    container_name: mongo
    restart: on-failure
    ports:
      - "27018:27017"
